#amlogic NEC remote GTMedia GT Combo

factory_code  = 0xfc030001
work_mode     = 0
repeat_enable = 1
repeat_delay  = 130
repeat_peroid = 120
release_delay = 20
debug_enable  = 0

fn_key_scancode = 0x03 # mouse
left_key_scancode = 0x57 # left
right_key_scancode = 0x53 # right
up_key_scancode = 0x47 # up
down_key_scancode = 0x4b # down
ok_key_scancode = 0x04 # ok

mouse_begin
    0 0x57 # left
    1 0x53 # right
    2 0x47 # up
    3 0x4b # down
mouse_end

key_begin
    0x11  116    #power
    
    0x1d  2      #1
    0x1c  3      #2
    0x46  4      #3
    0x15  5      #4
    0x14  6      #5
    0x45  7      #6
    0x00  8      #7
    0x1f  9      #8
    0x1b  10     #9
    0x0f  132    #recall
    0x1e  11     #0
    0x4c  14     #del
    
    0x4f  172    #home
    0x47  103    #up
    0x1a  63     #fav
    0x57  105    #left
    0x04  97     #ok
    0x53  106    #right
    0x43  46     #menu
    0x4b  108    #down
    0x52  1      #exit
    
    0x08  104    #page+
    # 0x4d voice
    0x5b  115    #vol+
    0x10  113    #mute
    0x5e  109    #page-
    # 0x4e custom
    0x49  114    #vol-
    
    0x13  24     #info (KEY_O, 23 is KEY_I)
    0x59  18     #epg
    0x03  388    #mouse
    0x0d  19     #fr
    0x44  51     #prev
    0x5f  57     #play/pause
    0x4a  33     #ff
    0x12  52     #next
    0x17  45     #stop
    0x5a  398    #red
    0x07  399    #green
    0x06  400    #yellow
    0x19  401    #blue
key_end

repeat_key_begin
    0x5b  115    #vol+
    0x49  114    #vol-
    0x47  103    #up
    0x57  105    #left
    0x53  106    #right
    0x4b  108    #down
repeat_key_end
